// Tunable simulation balance — single source for tick-loop constants.
// Content tables (build costs, raider types) stay in data.js.

export const BALANCE = {
  time: {
    minutesPerDay: 1440,
    dawnMinute: 360,
    nightStart: 1200,
    nightEnd: 320,
    raidSpawnMinute: 1150,
    traderArrive: 540,
    traderLeave: 1140,
    traderMinDay: 3,
    objectiveInterval: 15,
    cropGrowthInterval: 3,
    fireTickInterval: 2,
  },

  pop: {
    cap: 16,
    tier2: 6,
    tier3: 9,
    recruitMinDay: 3,
    recruitFoodMult: 3,
    foodlowMult: 2,
    mealsTargetMult: 2,
  },

  hunger: {
    rate: 0.075,
    gluttonMult: 1.5,
    winterMult: 1.25,
    cap: 100,
    eatTrigger: 72,
    mealRelief: 65,
    foodRelief: 46,
    eatMoraleBump: 0.3,
    starveHpDrain: 0.06,
    starveMoraleDrain: -0.01,
    cookMinFood: 4,
    cookCostFood: 2,
    cookMealsOut: 3,
  },

  crop: {
    growthRate: 0.23,
    mature: 100,
  },

  morale: {
    drift: 0.0004,
    base: 60,
    cheerfulBonus: 2,
    grimPenalty: 1,
    beaconBaseBonus: 5,
    stoutheartsBaseBonus: 5,
    high: 75,
    steady: 50,
    low: 35,
    breaking: 35,
    desertMax: 25,
    workHigh: 1.15,
    workLow: 0.8,
    eventMin: 3,
    eventCap: 6,
    eventWindow: 4,
    whyWindow: 3,
    death: -15,
    deathStouthearts: -8,
    warlordKill: 15,
    raidRepelled: 6,
    hordeBroken: 12,
    goodsStolen: -3,
    beaconLit: 20,
    winterEnd: 10,
    roughSleep: -0.003,
    victoryAbroad: 4,
    defeatAbroad: -5,
    deathAbroad: -8,
  },

  recruit: {
    daysHigh: 1,
    daysNormal: 2,
    desertMinPop: 3,
    desertChance: 0.6,
    desertFoodMax: 5,
    desertCoinMax: 3,
  },

  energy: {
    drain: 0.06,
    nightowlDrain: 0.015,
    restRough: 0.15,
    wakeFull: 99,
    wakeDay: 70,
    sleepTrigger: 25,
    sleepNight: 70,
    forceSleep: 12,
    cap: 100,
    idleHeal: 0.03,
  },

  work: {
    douse: 6,
    chop: 18,
    mine: 26,
    forage: 10,
    fish: 14,
    harvest: 8,
    cook: 10,
    craft: 12,
    repair: 8,
    cravenMult: 1.25,
    frailMult: 1.1,
    farmhandMult: 1.33,
    failCd: 20,
    repairWoodHp: 15,
    repairStoneHp: 25,
    fishCooldown: 500,
  },

  combat: {
    downChance: 0.5,
    downRecoverHp: 8,
    downHeal: 0.012,
    crawlCd: 4,
    medThreshold: 9,
    medHeal: 12,
    fireStandingDmg: 0.15,
    weaponBonus: 2,
    braveBonus: 2,
    keeneyeBonus: 2,
    guardRange: 6,
    guardRangeKeeneye: 8,
    guardAtkCd: 1,
    guardRangedCd: 2,
  },

  raid: {
    timerNormal: 420,
    timerHorde: 560,
    respawnDelayDays: 1,
    cooldownMin: 2,
    cooldownMax: 4,
    cooldownWinterExtra: 2,
    sizeBase: 2,
    sizeDayStart: 2,
    sizeDayStep: 3,
    banditReductionDiv: 2,
    unclearedFromDay: 8,
    unclearedMax: 3,
    winterReduction: 2,
    beaconBonus: 2,
    capEarly: 10,
    capLateFromDay: 20,
    capLateStep: 4,
    hordeBonus: 3,
    hordeFloorBase: 4,
    hordeFloorDiv: 3,
    warlordExtra: 1,
    jitterMax: 1,
    twoFrontFromDay: 14,
    twoFrontChance: 0.4,
    bruteFromDay: 6,
    bruteChance: 0.18,
    bruteHordeChance: 0.3,
    skirmisherFromDay: 9,
    skirmisherChance: 0.25,
    torcherFromDay: 11,
    torcherChance: 0.2,
    pathStale: 14,
    skirmisherPathStale: 10,
    torcherPathStale: 12,
    skirmisherFleeHp: 5,
    skirmisherSkulkChance: 0.5,
    torchIgniteCd: 6,
    torchFleeChance: 0.2,
    torchWanderChance: 0.5,
    torchLogChance: 0.25,
    fleeTimeout: 30,
    trapDmg: 7,
    trapDestroyChance: 0.65,
  },

  beacon: {
    holdDays: 3,
    raidPullDays: 1,
    banditQuietDays: 5,
  },

  fire: {
    initialBurn: 90,
    decay: 2,
    structDmg: 1,
    spreadChance: 0.02,
  },

  yields: {
    chopWood: [2, 4],
    mineStone: [2, 3],
    forageHerbs: 2,
    fishWinter: [1, 2],
    fishNormal: [2, 4],
    harvestFood: [3, 5],
    warlordCoin: [6, 12],
    skirmisherFood: [4, 8],
    skirmisherCoin: [2, 5],
  },
};
